// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iegvjpgwzibnpsjohyrr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImllZ3ZqcGd3emlibnBzam9oeXJyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3NTIzMjksImV4cCI6MjA3MDMyODMyOX0.9K_dt0meaUE3M2OzcznNRuPdB5foaXGHgNx8q0PdapY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});